### ISSUE TITLE
After an update of the Windows Sandbox, I can no longer use "run itunewin in sandbox."

### ISSUE THREAD

**Issue by Simofi** [damienvanrobaeys/Run-in-Sandbox#58]
After an update of the Windows Sandbox, I can no longer use "run itunewin in sandbox." I have already tried removing and reinstalling the structure, but the error persists.
![Screenshot 2024-11-14 145757](https://github.com/user-attachments/assets/af832a4f-cbc7-4591-92bf-8edfb2fadd68)

**Comment by Joly0** [comment]
Seems like a known bug in windows 11 24h2, not much we can do

**Comment by royklo** [comment]
same for me on Windows 24H2.

![image](https://github.com/user-attachments/assets/70e0ee96-1464-47df-8636-8aad33735f2f)

**Comment by aaronc222** [comment]
MemoryInMB is blank in the .wsb that is generated. The latest version of Sandbox apparently doesn't like this setting being blank.

Filling in a value for MemoryInMB in the RunInSandbox config C:\ProgramData\Run_in_Sandbox\Sandbox_Config.xml got it running again for me on Win 11 24H2 December CU.

**Comment by Joly0** [comment]
Hey @aaronc222 thanks for the useful information. Could you test what happens when you remove the line from the wsb file? So no memory limit is set? It should configure it automatically then

**Comment by aaronc222** [comment]
@Joly0, with the setting completely removed from the .wsb, Sandbox starts properly.

**Comment by Joly0** [comment]
Ok, thank you for testing. I am probably going to add an option that removes the line from the final wsb file, if the value is empty. That would leave the option open for users to configure it but will not bug out the sandbox without it. 
But as the original creator here doesnt actively work on run in sandbox anymore and doesnt reply to my mails, this will probably only be fixed on my fork, not here.

I´ll let you know, when i have implemented this and maybe you can test it.

**Comment by Joly0** [comment]
Hey @aaronc222 I think it should also be possible to set "MemoryInMB" to "Default" as some other values are. Could you try if that works aswell? If so this would make it even easier and i wont need to add some proper handling for this

**Comment by aaronc222** [comment]
Responded under your fork as well. Default did not work and gives the error from OP in this thread.

**Comment by moonnoonn** [comment]
I modify the Sandbox_Config.xml by adding 16384 (16gig) which solved the problem and Windows Sandbox was able to start. Deleting the MemoryInMB line did not resolve the issue. I'm on Windows 11 24H2

```
<MemoryInMB>16384</MemoryInMB> <!-- The amount of memory, in megabytes, to assign to the sandbox. -->
```

**Comment by Joly0** [comment]
Hey @moonnoonn 
The issue was solved over at my fork here https://github.com/Joly0/Run-in-Sandbox
Please give it a try and see, if that solves your issue :)

**Comment by royklo** [comment]
@Joly0 tried your fork, but ended up in the same error..

**Comment by Joly0** [comment]
> @Joly0 tried your fork, but ended up in the same error..

Do you mind creating an issue over at my fork for this issue and provide as much useful information as possible?

**Comment by LickABrick** [comment]
A colleague of mine got a message today when starting Windows Sandbox saying Sandbox would be updated (Win11 24H2), after the Sandbox update the Run in Sandbox context menu items worked again.

Hope this solves the issue for others in here too.

**Comment by Liridon-Alt-F4** [comment]
After fixing the Error MemoryInMB i got a different error. There seems to be an error while initializing Windows Sandbox. Any recommendations?

![Image](https://github.com/user-attachments/assets/4e90230b-0695-45cd-b22b-cee724f519dc)

**Comment by Joly0** [comment]
> After fixing the Error MemoryInMB i got a different error. There seems to be an error while initializing Windows Sandbox. Any recommendations?
> 
> ![Image](https://github.com/user-attachments/assets/4e90230b-0695-45cd-b22b-cee724f519dc)

Hey, have you tried my for over at https://github.com/Joly0/Run-in-Sandbox already?
Otherwise can you send me the .wsb file for that?

**Comment by Liridon-Alt-F4** [comment]
Heyy i just have tried it but i still recieve the same error.
Where is the .wsb file located?

**Comment by Joly0** [comment]
> Heyy i just have tried it but i still recieve the same error. Where is the .wsb file located?

Hey, should be under `C:\Users\YOURUSER\AppData\Local\Temp`

**Comment by Cyclone47** [comment]
@Joly0  @damienvanrobaeys  

There's currently a workaround to get sandbox to work by running it as admin; but this tool won't elevate as admin.

I have created a workaround that will run it elevated. Perhaps it's possible to add a second option in the windows Context menu: Run Elevated or something?

`<#
.SYNOPSIS
    Patches RunInSandbox.ps1 to self-elevate to admin before launching Windows Sandbox.
    Required for Windows 11 25H2+ where Sandbox needs admin rights.

.DESCRIPTION
    Run this script to inject a self-elevation block into RunInSandbox.ps1.
    It will auto-elevate to admin if needed and is safe to run multiple times.

.NOTES
    Date   : 2026-02-19
#>

$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
    [Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Start-Process -FilePath 'powershell.exe' -Verb RunAs -ArgumentList @(
        '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', "`"$PSCommandPath`""
    )
    exit
}

$scriptDir = Split-Path -Parent $PSCommandPath
$targetFile = Join-Path $scriptDir 'RunInSandbox.ps1'

if (-not (Test-Path -LiteralPath $targetFile)) {
    $targetFile = Join-Path $env:ProgramData 'Run_in_Sandbox\RunInSandbox.ps1'
}

if (-not (Test-Path -LiteralPath $targetFile)) {
    Write-Host "ERROR: Cannot find RunInSandbox.ps1" -ForegroundColor Red
    Write-Host "  Looked in: $scriptDir" -ForegroundColor Yellow
    Write-Host "  Looked in: $env:ProgramData\Run_in_Sandbox" -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 1
}

Write-Host "Target: $targetFile" -ForegroundColor Cyan


$raw = [System.IO.File]::ReadAllText($targetFile, [System.Text.Encoding]::UTF8)


if ($raw -match 'Self-elevate to admin') {
    Write-Host 'RunInSandbox.ps1 is already patched - nothing to do.' -ForegroundColor Green
    Read-Host "Press Enter to exit"
    exit 0
}


if ($raw -match "`r`n") { $EOL = "`r`n" } else { $EOL = "`n" }


$elevationLines = @'
$_isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
    [Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $_isAdmin) {
    $argList = @(
        '-NoProfile', '-ExecutionPolicy', 'Unrestricted', '-sta', '-WindowStyle', 'Hidden',
        '-File', "`"$PSCommandPath`"",
        '-Type', $Type,
        '-ScriptPath', "`"$ScriptPath`""
    )
    Start-Process -FilePath 'powershell.exe' -Verb RunAs -ArgumentList $argList
    exit
}
'@

$elevationBlock = $elevationLines.Replace("`r`n", "`n").Replace("`n", $EOL)


$needle = ")${EOL}${EOL}#Start-Transcript"
$replacement = ")${EOL}${EOL}${elevationBlock}${EOL}${EOL}#Start-Transcript"

$patched = $raw.Replace($needle, $replacement)

if ($patched -eq $raw) {
    Write-Host 'WARNING: Could not locate the insertion point.' -ForegroundColor Yellow
    Write-Host 'The file may have been modified or has an unexpected format.' -ForegroundColor Yellow
    Write-Host 'Please apply the patch manually.' -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 1
}


$bytes = [System.IO.File]::ReadAllBytes($targetFile)
$hasBOM = ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF)
$encoding = if ($hasBOM) { New-Object System.Text.UTF8Encoding $true } else { New-Object System.Text.UTF8Encoding $false }

[System.IO.File]::WriteAllText($targetFile, $patched, $encoding)

Write-Host '' 
Write-Host 'SUCCESS: RunInSandbox.ps1 has been patched to self-elevate to admin.' -ForegroundColor Green
Write-Host 'All "Run in Sandbox" context menu actions will now prompt for UAC elevation.' -ForegroundColor Cyan
Write-Host ''
Read-Host "Press Enter to exit"`

**Comment by Joly0** [comment]
> [@Joly0](https://github.com/Joly0) [@damienvanrobaeys](https://github.com/damienvanrobaeys)
> 
> There's currently a workaround to get sandbox to work by running it as admin; but this tool won't elevate as admin.
> 
> I have created a workaround that will run it elevated. Perhaps it's possible to add a second option in the windows Context menu: Run Elevated or something?
> 
> <# .SYNOPSIS Patches RunInSandbox.ps1 to self-elevate to admin before launching Windows Sandbox. Required for Windows 11 25H2+ where Sandbox needs admin rights.
> 
> .DESCRIPTION Run this script to inject a self-elevation block into RunInSandbox.ps1. It will auto-elevate to admin if needed and is safe to run multiple times.
> 
> .NOTES Date : 2026-02-19 #>
> 
> $isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole( [Security.Principal.WindowsBuiltInRole]::Administrator) if (-not $isAdmin) { Start-Process -FilePath 'powershell.exe' -Verb RunAs -ArgumentList @( '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', "`"$PSCommandPath`"" ) exit }
> 
> $scriptDir = Split-Path -Parent $PSCommandPath $targetFile = Join-Path $scriptDir 'RunInSandbox.ps1'
> 
> if (-not (Test-Path -LiteralPath $targetFile)) { $targetFile = Join-Path $env:ProgramData 'Run_in_Sandbox\RunInSandbox.ps1' }
> 
> if (-not (Test-Path -LiteralPath $targetFile)) { Write-Host "ERROR: Cannot find RunInSandbox.ps1" -ForegroundColor Red Write-Host " Looked in: $scriptDir" -ForegroundColor Yellow Write-Host " Looked in: $env:ProgramData\Run_in_Sandbox" -ForegroundColor Yellow Read-Host "Press Enter to exit" exit 1 }
> 
> Write-Host "Target: $targetFile" -ForegroundColor Cyan
> 
> $raw = [System.IO.File]::ReadAllText($targetFile, [System.Text.Encoding]::UTF8)
> 
> if ($raw -match 'Self-elevate to admin') { Write-Host 'RunInSandbox.ps1 is already patched - nothing to do.' -ForegroundColor Green Read-Host "Press Enter to exit" exit 0 }
> 
> if ($raw -match "`r`n") { $EOL = "`r`n" } else { $EOL = "`n" }
> 
> $elevationLines = @'
> # --- Self-elevate to admin (required for Windows Sandbox on 25H2+) ---
> 
> $_isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole( [Security.Principal.WindowsBuiltInRole]::Administrator) if (-not $_isAdmin) { $argList = @( '-NoProfile', '-ExecutionPolicy', 'Unrestricted', '-sta', '-WindowStyle', 'Hidden', '-File', "`"$PSCommandPath`"", '-Type', $Type, '-ScriptPath', "`"$ScriptPath`"" ) Start-Process -FilePath 'powershell.exe' -Verb RunAs -ArgumentList $argList exit } '@
> 
> $elevationBlock = $elevationLines.Replace("`r`n", "`n").Replace("`n", $EOL)
> 
> n e e d l e = " ) {EOL}${EOL}#Start-Transcript" r e p l a c e m e n t = " ) {EOL}${EOL}${elevationBlock}${EOL}${EOL}#Start-Transcript"
> 
> $patched = $raw.Replace($needle, $replacement)
> 
> if ($patched -eq $raw) { Write-Host 'WARNING: Could not locate the insertion point.' -ForegroundColor Yellow Write-Host 'The file may have been modified or has an unexpected format.' -ForegroundColor Yellow Write-Host 'Please apply the patch manually.' -ForegroundColor Yellow Read-Host "Press Enter to exit" exit 1 }
> 
> $bytes = [System.IO.File]::ReadAllBytes($targetFile) $hasBOM = ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) $encoding = if ($hasBOM) { New-Object System.Text.UTF8Encoding $true } else { New-Object System.Text.UTF8Encoding $false }
> 
> [System.IO.File]::WriteAllText($targetFile, $patched, $encoding)
> 
> Write-Host '' Write-Host 'SUCCESS: RunInSandbox.ps1 has been patched to self-elevate to admin.' -ForegroundColor Green Write-Host 'All "Run in Sandbox" context menu actions will now prompt for UAC elevation.' -ForegroundColor Cyan Write-Host '' Read-Host "Press Enter to exit"

Interesting. I didnt knew that, but good to know now. Just some things i want to mention:
1. It would help with readability, if you would put your code into code-blocks here in github
2. I would not like to add any new options for the right-click menu that are there to act as a workaround for a bug. I would prefer if this was an optional setting configured through the sandbox_config.xml file.
3. Not sure if i read your unformatted code correctly, but it appears to me, that you are just restarting the run-in-sandbox.ps1 script as admin again after startup. This is unneeded as far as i know. As you explained, only the sandbox needs to be started as admin and as the sandbox itself is started using the command `Start-Process -FilePath $Sandbox_File_Path -Wait` it would be as simple as checking if the variable in the config file is set and then add the `-Verb runAs` to the `Start-Process` command

**Comment by Cyclone47** [comment]
@Joly0 I think my 'ai' proposal to neaten this up may have overcomplicated it by a LOT.
My first attempt was indeed more aligned with your number 3 and was as simple as relacing 
`Start-Process -FilePath $Sandbox_File_Path -Wait` 
by 
`Start-Process -FilePath "C:\Windows\System32\WindowsSandbox.exe" -ArgumentList $Sandbox_File_Path -Verb RunAs -Wait`
